spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    type: simple

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms  # 연결 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결 수
          max-idle: 5  # 최대 유휴 연결 수
          min-idle: 1  # 최소 유휴 연결 수
          max-wait: 2000ms  # 최대 대기 시간

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  signup-redirect-uri: ${KAKAO_SIGNUP_REDIRECT_URI}
  login-redirect-uri: ${KAKAO_LOGIN_REDIRECT_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  user-info-uri: ${KAKAO_USER_INFO_URI}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.pigma.harusari

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 30분
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 7일

server:
  port: ${SERVER_PORT}

gemini:
  api-key: ${AI_KEY}
  base-url: https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash-lite:generateContent
