spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms  # 연결 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결 수
          max-idle: 5  # 최대 유휴 연결 수
          min-idle: 1  # 최소 유휴 연결 수
          max-wait: 2000ms  # 최대 대기 시간

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.pigma.harusari

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 30분
  refresh-expiration : ${JWT_REFRESH_EXPIRATION} # 7일

server:
  port: ${SERVER_PORT}